// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContentHandleRequest {
    #[prost(fixed32, required, tag = "1")]
    pub program: u32,
    #[prost(fixed32, required, tag = "2")]
    pub stream: u32,
    #[prost(fixed32, optional, tag = "3", default = "1701729619")]
    pub version: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTitleIconsRequest {
    #[prost(uint32, repeated, tag = "1")]
    pub title_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub usage: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub version: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTitleIconsResponse {
    #[prost(message, repeated, tag = "1")]
    pub title_icon_content_handles: ::prost::alloc::vec::Vec<
        super::super::TitleIconContentHandle,
    >,
}
