// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientSdkVersionInfo {
    #[prost(string, optional, tag = "1")]
    pub sdk_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub sdk_version: ::core::option::Option<super::super::SemanticVersion>,
    #[prost(message, optional, tag = "3")]
    pub protocol_version: ::core::option::Option<super::super::SemanticVersion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectRequest {
    #[prost(message, optional, tag = "1")]
    pub client_id: ::core::option::Option<super::super::ProcessId>,
    #[prost(message, optional, tag = "2")]
    pub bind_request: ::core::option::Option<BindRequest>,
    #[prost(bool, optional, tag = "3", default = "true")]
    pub use_bindless_rpc: ::core::option::Option<bool>,
    #[prost(enumeration = "MeteringLevel", optional, tag = "4")]
    pub metering_level: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "5")]
    pub client_sdk_info: ::core::option::Option<ClientSdkVersionInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionMeteringContentHandles {
    #[prost(message, repeated, tag = "1")]
    pub content_handle: ::prost::alloc::vec::Vec<super::super::ContentHandle>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectResponse {
    #[prost(message, required, tag = "1")]
    pub server_id: super::super::ProcessId,
    #[prost(message, optional, tag = "2")]
    pub client_id: ::core::option::Option<super::super::ProcessId>,
    #[prost(uint32, optional, tag = "3")]
    pub bind_result: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "4")]
    pub bind_response: ::core::option::Option<BindResponse>,
    #[prost(message, optional, tag = "5")]
    pub content_handle_array: ::core::option::Option<ConnectionMeteringContentHandles>,
    #[prost(uint64, optional, tag = "6")]
    pub server_time: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "7", default = "false")]
    pub use_bindless_rpc: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "8")]
    pub binary_content_handle_array: ::core::option::Option<
        ConnectionMeteringContentHandles,
    >,
    #[prost(string, optional, tag = "9")]
    pub ciid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "10")]
    pub connected_region: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoundService {
    #[prost(fixed32, required, tag = "1")]
    pub hash: u32,
    #[prost(uint32, required, tag = "2")]
    pub id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindRequest {
    #[deprecated]
    #[prost(fixed32, repeated, tag = "1")]
    pub deprecated_imported_service_hash: ::prost::alloc::vec::Vec<u32>,
    #[deprecated]
    #[prost(message, repeated, tag = "2")]
    pub deprecated_exported_service: ::prost::alloc::vec::Vec<BoundService>,
    #[prost(message, repeated, tag = "3")]
    pub exported_service: ::prost::alloc::vec::Vec<BoundService>,
    #[prost(message, repeated, tag = "4")]
    pub imported_service: ::prost::alloc::vec::Vec<BoundService>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindResponse {
    #[deprecated]
    #[prost(uint32, repeated, tag = "1")]
    pub imported_service_id: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoRequest {
    #[prost(fixed64, optional, tag = "1")]
    pub time: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "2", default = "false")]
    pub network_only: ::core::option::Option<bool>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub payload: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "4")]
    pub forward: ::core::option::Option<super::super::ProcessId>,
    #[prost(string, optional, tag = "5")]
    pub forward_client_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoResponse {
    #[prost(fixed64, optional, tag = "1")]
    pub time: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub payload: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisconnectRequest {
    #[prost(uint32, required, tag = "1")]
    pub error_code: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisconnectNotification {
    #[prost(uint32, required, tag = "1")]
    pub error_code: u32,
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptRequest {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MeteringLevel {
    Legacy = 0,
    Categorized = 1,
}
impl MeteringLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Legacy => "METERING_LEVEL_LEGACY",
            Self::Categorized => "METERING_LEVEL_CATEGORIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "METERING_LEVEL_LEGACY" => Some(Self::Legacy),
            "METERING_LEVEL_CATEGORIZED" => Some(Self::Categorized),
            _ => None,
        }
    }
}
