// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Friend {
    #[prost(message, required, tag = "1")]
    pub account_id: super::super::EntityId,
    #[prost(message, repeated, tag = "2")]
    pub attribute: ::prost::alloc::vec::Vec<super::super::Attribute>,
    #[prost(uint32, repeated, tag = "3")]
    pub role: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, optional, tag = "4")]
    pub privileges: ::core::option::Option<u64>,
    #[deprecated]
    #[prost(uint64, optional, tag = "5")]
    pub attributes_epoch: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "6")]
    pub creation_time: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FriendOfFriend {
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
    #[prost(uint32, repeated, tag = "3")]
    pub role: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, optional, tag = "4")]
    pub privileges: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "6")]
    pub full_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub battle_tag: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceivedInvitation {
    #[prost(fixed64, required, tag = "1")]
    pub id: u64,
    #[prost(message, required, tag = "2")]
    pub inviter_identity: super::super::Identity,
    #[prost(message, required, tag = "3")]
    pub invitee_identity: super::super::Identity,
    #[prost(string, optional, tag = "4")]
    pub inviter_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub invitee_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "7")]
    pub creation_time: ::core::option::Option<u64>,
    #[prost(fixed32, optional, tag = "9")]
    pub program: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendInvitation {
    #[prost(uint32, repeated, tag = "2")]
    pub role: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "3")]
    pub attribute: ::prost::alloc::vec::Vec<super::super::Attribute>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SentInvitation {
    #[prost(fixed64, optional, tag = "1")]
    pub id: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "2")]
    pub target_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub role: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "4")]
    pub attribute: ::prost::alloc::vec::Vec<super::super::Attribute>,
    #[prost(uint64, optional, tag = "5")]
    pub creation_time: ::core::option::Option<u64>,
    #[prost(fixed32, optional, tag = "6")]
    pub program: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendInvitationParams {
    #[prost(string, optional, tag = "1")]
    pub target_email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub target_battle_tag: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag = "6")]
    pub role: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "8")]
    pub attribute: ::prost::alloc::vec::Vec<super::super::Attribute>,
    #[prost(string, optional, tag = "9")]
    pub target_name: ::core::option::Option<::prost::alloc::string::String>,
    #[deprecated]
    #[prost(fixed32, optional, tag = "10")]
    pub program: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "11")]
    pub target_phone_number: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeResponse {
    #[deprecated]
    #[prost(uint32, optional, tag = "1")]
    pub max_friends: ::core::option::Option<u32>,
    #[deprecated]
    #[prost(uint32, optional, tag = "2")]
    pub max_received_invitations: ::core::option::Option<u32>,
    #[deprecated]
    #[prost(uint32, optional, tag = "3")]
    pub max_sent_invitations: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "4")]
    pub role: ::prost::alloc::vec::Vec<super::super::Role>,
    #[prost(message, repeated, tag = "5")]
    pub friends: ::prost::alloc::vec::Vec<Friend>,
    #[prost(message, repeated, tag = "7")]
    pub received_invitations: ::prost::alloc::vec::Vec<ReceivedInvitation>,
    #[prost(message, repeated, tag = "8")]
    pub sent_invitations: ::prost::alloc::vec::Vec<SentInvitation>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcceptInvitationOptions {
    #[prost(uint32, optional, tag = "1")]
    pub role: ::core::option::Option<u32>,
    #[prost(fixed32, optional, tag = "2")]
    pub program: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(uint64, required, tag = "2")]
    pub object_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsubscribeRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(uint64, optional, tag = "2")]
    pub object_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendInvitationRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_identity: ::core::option::Option<super::super::Identity>,
    #[prost(message, required, tag = "2")]
    pub target_id: super::super::EntityId,
    #[prost(message, required, tag = "3")]
    pub params: super::super::InvitationParams,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeInvitationRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(fixed64, optional, tag = "2")]
    pub invitation_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcceptInvitationRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(fixed64, required, tag = "3")]
    pub invitation_id: u64,
    #[prost(message, optional, tag = "4")]
    pub options: ::core::option::Option<AcceptInvitationOptions>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeclineInvitationRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(fixed64, required, tag = "3")]
    pub invitation_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IgnoreInvitationRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(fixed64, required, tag = "3")]
    pub invitation_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveFriendRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(message, required, tag = "2")]
    pub target_id: super::super::EntityId,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeAllInvitationsRequest {
    #[prost(message, optional, tag = "2")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ViewFriendsRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(message, required, tag = "2")]
    pub target_id: super::super::EntityId,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewFriendsResponse {
    #[prost(message, repeated, tag = "1")]
    pub friends: ::prost::alloc::vec::Vec<FriendOfFriend>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFriendStateRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(message, required, tag = "2")]
    pub target_id: super::super::EntityId,
    #[prost(message, repeated, tag = "3")]
    pub attribute: ::prost::alloc::vec::Vec<super::super::Attribute>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFriendListRequest {
    #[prost(message, optional, tag = "2")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFriendListResponse {
    #[prost(message, repeated, tag = "1")]
    pub friends: ::prost::alloc::vec::Vec<Friend>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFriendshipRequest {
    #[prost(message, optional, tag = "1")]
    pub agent_id: ::core::option::Option<super::super::EntityId>,
    #[prost(message, optional, tag = "2")]
    pub target_id: ::core::option::Option<super::super::EntityId>,
    #[prost(uint32, repeated, tag = "3")]
    pub role: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendNotification {
    #[prost(message, required, tag = "1")]
    pub target: Friend,
    #[prost(message, optional, tag = "5")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFriendStateNotification {
    #[prost(message, required, tag = "1")]
    pub changed_friend: Friend,
    #[prost(message, optional, tag = "5")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvitationNotification {
    #[prost(message, required, tag = "1")]
    pub invitation: ReceivedInvitation,
    #[prost(uint32, optional, tag = "3", default = "0")]
    pub reason: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "5")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SentInvitationAddedNotification {
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
    #[prost(message, optional, tag = "2")]
    pub invitation: ::core::option::Option<SentInvitation>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SentInvitationRemovedNotification {
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<super::super::EntityId>,
    #[prost(fixed64, optional, tag = "2")]
    pub invitation_id: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "3")]
    pub reason: ::core::option::Option<u32>,
}
