#![allow(deprecated, unused)]
#![allow(clippy::deprecated)]

mod util;

use itertools::Itertools;
use anyhow::Result;
use std::collections::HashSet;
use std::hash::Hash;
use std::str::FromStr;
use crate::proto::bgs::protocol::{BgsMethodOptions, BgsServiceOptions};
use proc_macro2::{Literal, TokenStream};
use prost_reflect::prost::Message;
use prost_reflect::prost_types::FileDescriptorSet;
use prost_reflect::{DynamicMessage, EnumDescriptor, ExtensionDescriptor, FileDescriptor, MessageDescriptor, MethodDescriptor, ReflectMessage, ServiceDescriptor};
use quote::{ToTokens, TokenStreamExt, format_ident, quote};
use syn::{Ident, Path, UsePath, parse_str};
use syn::token::Type;
use crate::util::find_extension;

pub mod proto {
    use prost_reflect::DescriptorPool;
    use std::sync::LazyLock;

    pub static DESCRIPTOR_POOL: LazyLock<DescriptorPool> = LazyLock::new(|| DescriptorPool::decode(
        include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin")).as_ref()
    ).unwrap());

    include!("proto/proto.rs");
}

struct Generator {
    pub fds: Vec<FileDescriptorSet>,
}

fn to_type_parts(desc: &MessageDescriptor) -> Result<(Path, Ident)> {
    dbg!(desc);

    let package = parse_str(desc.package_name().replace(".", "::").as_str())?;
    let name = parse_str(desc.name())?;

    Ok((package, name))
}

fn decode<T: Message + Default>(value: &DynamicMessage) -> Option<T> {
    T::decode(value.encode_to_vec().as_slice()).ok()
}

fn hash(data: &[u8]) -> u32 {
    data.into_iter().fold(0x811C9DC5, |acc, c| (acc ^ (*c as u32)).wrapping_mul(0x1000193))
}

#[derive(Default)]
struct MethodInfo {
    /// The method. This can either be its declaration (eg a trait method) or its implementation.
    implementation: TokenStream,
    dependencies: Vec<String>,
}

/// A package combines source as an AST, and the relative path of the module that contains it.
/// In its purest form, this is just a file that has not yet been emitted to disk.
struct Package {
    source: TokenStream,
    module: Vec<String>,
}

/// Holds a type as well as the package that contains it.
#[derive(Eq, PartialEq, Ord, PartialOrd, Hash)]
struct DependencyInfo {
    /// The complete path where this type lives.
    path: String,

    /// The name of this type.
    typename: String
}

impl DependencyInfo {
    pub fn from(desc: MessageDescriptor) -> Self {
        Self {
            path: desc.package_name().to_string(),
            typename: desc.name().to_string(),
        }
    }
}

impl ToTokens for DependencyInfo {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let path = parse_str::<Path>(self.path.replace(".", "::").as_str())
            .expect("invalid path");
        let name = format_ident!("{}", &self.typename);

        tokens.append_all(quote! {
            use crate::#path::#name;
        });
    }
}

impl Generator {
    fn render_file_descriptor(fd: &FileDescriptor) -> TokenStream {
        let messages = fd.messages().map(Self::render_message);
        let enums = fd.enums().map(Self::render_enum);
        let services = fd.services().map(Self::render_service);
        let extensions = fd.extensions().map(Self::render_extension);

        quote! {
            // Generated by protogen. Do not edit.
            use anyhow::Result;

            #(#services)*
        }
    }

    fn render_message(msg: MessageDescriptor) -> TokenStream {
        todo!()
    }

    fn render_enum(enm: EnumDescriptor) -> TokenStream {
        todo!()
    }

    fn render_service(svc: ServiceDescriptor) -> TokenStream {
        let name = format_ident!("{}", svc.name());
        let full_name = svc.full_name();

        let make_token_hash= |name: &[u8]| {
            let hash = hash(name);
            Literal::from_str(
                &format!("0x{:X}u32", hash)
            ).unwrap()
        };

        let original_hash = find_extension(&svc, "bgs.protocol.service_options")
            .map(|extension: BgsServiceOptions| {
                let hash = make_token_hash(extension.descriptor_name.expect("Missing descriptor name").as_bytes());

                quote! {
                    const ORIGINAL_HASH: u32 = #hash;
                }
            }).unwrap_or(quote! { });

        let name_hash = make_token_hash(full_name.as_bytes());

        let (methods, imports) = svc.methods()
            .map(Self::render_handler)
            .fold((quote! {}, HashSet::new()), |(code, mut imports), (function, paths)| {
                let imports = imports.into_iter()
                    .chain(paths.into_iter())
                    .collect();

                (quote! {
                    #code

                    #function
                }, imports)
            });

        let imports: Vec<_> = imports.into_iter()
            .sorted()
            .collect();

        // Generate parsers and handler calls.
        let parse_blocks: Vec<_> = svc.methods()
            .filter_map(Self::render_parse_block)
            .collect();

        quote! {
            #(#imports)*

            pub trait #name {
                #original_hash
                const NAME_HASH: u32 = #name_hash;

                #methods

                pub fn call_server_method(&mut self, token: u32, method: u32, stream: &mut Source)
                    -> impl Future<Output = Result<()>>
                {
                    match (method & 0x3FFFFFFFu32) {
                        #(#parse_blocks),*
                        _ => {
                            self.send_error_response("ERROR_RPC_INVALID_METHOD")
                        }
                    }
                }
            }
        }
    }

    fn render_parse_block(md: MethodDescriptor) -> Option<TokenStream> {
        find_extension(&md, "bgs.protocol.method_options")
            .and_then(|o: BgsMethodOptions| o.id)
            .map(|method_id| {
                let input = format_ident!("{}", md.input().name());
                let handler_name = format_ident!("handle_{}", md.input().name());


                // Externally provided arguments: `method` and `token`.
                quote! {
                    #method_id => {
                        match <#input>::decode(buffer) {
                            Ok(request) => {
                                match #handler_name(request) {
                                    Ok(response) => todo!("Send response body"),
                                    Err(status) => {
                                        todo!("Send the status code")
                                    }
                                }
                            },
                            Err(_) => {
                                todo!("ERROR_RPC_MALFORMED_REQUEST")
                            }
                        }
                    }
                }
            })
    }

    /// Renders a [`MethodDescriptor`] into a [`TokenStream`] as well as a collection of all packages
    /// and types needed.
    fn render_handler(md: MethodDescriptor) -> (TokenStream, Vec<DependencyInfo>) {
        assert!(!md.is_client_streaming() && !md.is_server_streaming());

        let (_, input_name) = to_type_parts(&md.input())
            .expect("Failed to parse input type");
        let (_, output_name) = to_type_parts(&md.output())
            .expect("Failed to parse output type");

        let handle_name = format_ident!("Handle{}", md.name());

        let input = DependencyInfo::from(md.input());
        let output = DependencyInfo::from(md.output());

        (quote! {
            fn #handle_name(&mut self, msg: #input_name) -> impl Future<Output = Result<#output_name>> {
                async {
                    self.send_error_code("ERROR_RPC_NOT_IMPLEMENTED")
                }
            }
        }, vec![input, output])
    }

    fn render_extension(ext: ExtensionDescriptor) -> TokenStream {
        todo!()
    }
}

#[cfg(test)]
mod test {
    use crate::proto::DESCRIPTOR_POOL;
    use crate::Generator;

    use assert_tokens_eq::assert_tokens_eq;
    use quote::quote;
    use crate::proto::bgs::protocol::account::v1::GetAccountInfoRequest;

    #[test]
    pub fn test_service() {
        let fd = DESCRIPTOR_POOL.files()
            .find(|f| f.name() == "bgs/low/pb/client/account_service.proto")
            .expect("Could not find account_service.proto");

        fd.services().take(1).for_each(|svc| {
            let outcome = Generator::render_service(svc);

            assert_tokens_eq! { outcome, quote! {
                pub trait AccountService {
                    const ORIGINAL_HASH: u32 = 0x62DA0891u32;
                    const NAME_HASH: u32 = 0x1E4DC42Fu32;
                }
            } }
        });
    }
}