// This file contains all the protobuf files that need to be parsed.
// It is used both by the build-script and this crate itself.
// We use Prost to generate intermediary types for the crate itself;
// the crate then uses Prost-generated code to emit Protobuf types
// as well as service implementations, since that is currently impossible
// to do from the Protobuf crate itself (as well as extensions).

pub const PROTOS: [&str; 72] = [
    "bgs/low/pb/client/account_service.proto",
    "bgs/low/pb/client/account_types.proto",
    "bgs/low/pb/client/attribute_types.proto",
    "bgs/low/pb/client/authentication_service.proto",
    "bgs/low/pb/client/challenge_service.proto",
    "bgs/low/pb/client/content_handle_types.proto",
    "bgs/low/pb/client/connection_service.proto",
    "bgs/low/pb/client/embed_types.proto",
    "bgs/low/pb/client/entity_types.proto",
    "bgs/low/pb/client/ets_types.proto",
    "bgs/low/pb/client/event_view_types.proto",
    "bgs/low/pb/client/friends_service.proto",
    "bgs/low/pb/client/friends_types.proto",
    "bgs/low/pb/client/game_utilities_service.proto",
    "bgs/low/pb/client/game_utilities_types.proto",
    "bgs/low/pb/client/invitation_types.proto",
    "bgs/low/pb/client/message_types.proto",
    "bgs/low/pb/client/notification_types.proto",
    "bgs/low/pb/client/presence_listener.proto",
    "bgs/low/pb/client/presence_service.proto",
    "bgs/low/pb/client/presence_types.proto",
    "bgs/low/pb/client/profanity_filter_config.proto",
    "bgs/low/pb/client/resource_service.proto",
    "bgs/low/pb/client/role_types.proto",
    "bgs/low/pb/client/rpc_config.proto",
    "bgs/low/pb/client/rpc_types.proto",
    "bgs/low/pb/client/semantic_version.proto",
    "bgs/low/pb/client/voice_types.proto",

    "bgs/low/pb/client/api/client/v1/block_list_listener.proto",
    "bgs/low/pb/client/api/client/v1/block_list_service.proto",
    "bgs/low/pb/client/api/client/v1/block_list_types.proto",
    "bgs/low/pb/client/api/client/v1/channel_id.proto",
    "bgs/low/pb/client/api/client/v1/channel_types.proto",
    "bgs/low/pb/client/api/client/v1/club_membership_service.proto",
    "bgs/low/pb/client/api/client/v1/club_membership_types.proto",
    "bgs/low/pb/client/api/client/v1/club_stream.proto",
    "bgs/low/pb/client/api/client/v1/club_types.proto",
    "bgs/low/pb/client/api/client/v1/club_member.proto",
    "bgs/low/pb/client/api/client/v1/club_invitation.proto",
    "bgs/low/pb/client/api/client/v1/club_enum.proto",
    "bgs/low/pb/client/api/client/v1/club_role.proto",
    "bgs/low/pb/client/api/client/v1/club_range_set.proto",
    "bgs/low/pb/client/api/client/v1/club_core.proto",
    "bgs/low/pb/client/api/client/v1/club_ban.proto",
    "bgs/low/pb/client/api/client/v1/club_name_generator.proto",

    "bgs/low/pb/client/api/client/v2/notification_service.proto",
    "bgs/low/pb/client/api/client/v2/notification_types.proto",
    "bgs/low/pb/client/api/client/v2/report_service.proto",
    "bgs/low/pb/client/api/client/v2/report_types.proto",
    "bgs/low/pb/client/api/client/v2/whisper_listener.proto",
    "bgs/low/pb/client/api/client/v2/whisper_service.proto",

    "bgs/low/pb/client/api/common/v1/club_enum.proto",
    "bgs/low/pb/client/api/common/v1/club_tag.proto",
    "bgs/low/pb/client/api/common/v1/club_type.proto",
    "bgs/low/pb/client/api/common/v1/club_core.proto",
    "bgs/low/pb/client/api/common/v1/club_member_id.proto",
    "bgs/low/pb/client/api/common/v1/embed_types.proto",
    "bgs/low/pb/client/api/common/v1/event_view_types.proto",
    "bgs/low/pb/client/api/common/v1/invitation_types.proto",
    "bgs/low/pb/client/api/common/v1/message_types.proto",
    "bgs/low/pb/client/api/common/v1/voice_types.proto",

    "bgs/low/pb/client/api/common/v2/attribute_types.proto",
    "bgs/low/pb/client/api/common/v2/game_account_handle.proto",
    "bgs/low/pb/client/api/common/v2/whisper_types.proto",

    "bgs/low/pb/client/global_extensions/field_options.proto",
    "bgs/low/pb/client/global_extensions/message_options.proto",
    "bgs/low/pb/client/global_extensions/method_options.proto",
    "bgs/low/pb/client/global_extensions/range.proto",
    "bgs/low/pb/client/global_extensions/register_method_types.proto",
    "bgs/low/pb/client/global_extensions/routing.proto",
    "bgs/low/pb/client/global_extensions/service_options.proto",

    "google/protobuf/descriptor.proto",
];
